### PR TITLE
Set up project from Elixir template

### LINKED ISSUE #2: Init project from Elixir template
## Why

For better productivity it is advisable to use the same project template across all company projects.

## Acceptance Criteria

Project was initialized with using [Elixir template](https://github.com/nimblehq/elixir-templates) and can be run locally.

### PR DESCRIPTION
**Pull request by Nihisil**
Resolves #2 

## What happened

Set up a new project from Nimble's Elixir template.

The PR doesn't have CI/CD configuration yet, it will be done as a separate PR.
 
## Insight

Web version of the template was used to set up the project.
 
## Proof Of Work

image

### CODE REVIEW

**Comment by longnd** [comment]
> The PR doesn't have CI/CD configuration yet, it will be done as a separate PR.

it actually has CI & CD already: we're using Github action workflows to build and run the tests. Also, once a PR is merged to the `develop` branch, it will be deployed to Heroku.
https://github.com/Nihisil/nimble-certification-elixir/tree/chore/init-project-from-template/.github/workflows

but it will not work now as there are still some preparation steps you need to do
https://github.com/Nihisil/nimble-certification-elixir/blob/chore/init-project-from-template/.github/workflows/README.md

I assume that's what you want to tackle in a separate PR? 🤔

**Comment by Nihisil** [comment]
> I assume that's what you want to tackle in a separate PR? 🤔

Yep, in separate PR I wanted to set up all credentials and make sure that tests and linters are working correctly (right now one test fails for some reason).

I saw that we have GitHub action files in the template, but wanted to separate these two tasks.

**Review by bterone — APPROVED** [review]

**Review by junan — APPROVED** [review]

**Comment by junan** [comment]
Screen Shot 2022-05-10 at 12 40 03 PM

@Nihisil We can set the `chore` Label

**Comment by Nihisil** [comment]
> We can set the `chore` Label

So, label should be assigned to the issue ticket and to the PR as well. Got it.

**Pull request merged**
